export type Apartment = {
  id: number;
  title: string;
  description: string;
  city: string;
  address: string;
  neighborhood: string;
  price: number;
  bedrooms: number;
  bathrooms: number;
  squareMeters: number;
  contact: string;
  petFriendly: boolean;
  availableFrom: string;
  propertyType: string;
  new: boolean;
  images: string[];
  lat: number;
  lng: number;
};
